In [76]:
import pandas as pd
from bs4 import BeautifulSoup
import urllib.request as ur

In [124]:
index = 'TSLA'
url_is = 'https://finance.yahoo.com/quote/' + index + '/financials?p=' + index
url_bs = 'https://finance.yahoo.com/quote/' + index + '/balance-sheet?p=' + index
url_cf = 'https://finance.yahoo.com/quote/' + index + '/cash-flow?p=' + index

# open link and read into lxml format. 
# read_data = ur.urlopen(url_is).read()
read_data = ur.urlopen(url_bs).read()
soup_is = BeautifulSoup(read_data, 'lxml')

# empty list
ls = []
# find all data structure that is 'div'
for l in soup_is.find_all('div'):
    ls.append(l.string)

    

new_ls = list(filter(None, ls))

In [125]:
new_ls = new_ls[32:]
is_data = list(zip(*[iter(new_ls)]*5))
is_data

[('Total Capitalization',
  '18,252,000',
  '14,326,915',
  '13,655,631',
  '10,731,195'),
 ('Common Stock Equity', '6,618,000', '4,923,243', '4,237,242', '4,752,911'),
 ('Capital Lease Obligations',
  '1,050,000',
  '1,855,900',
  '1,801,010',
  '1,459,684'),
 ('Net Tangible Assets', '6,081,000', '4,572,592', '3,815,503', '4,376,766'),
 ('Working Capital', '1,436,000', '-1,685,828', '-1,104,150', '432,791'),
 ('Invested Capital', '20,037,000', '16,894,614', '14,552,180', '11,881,342'),
 ('Tangible Book Value', '6,081,000', '4,572,592', '3,815,503', '4,376,766'),
 ('Total Debt', '14,469,000', '13,827,271', '12,115,948', '8,588,115'),
 ('Net Debt', '7,151,000', '8,285,753', '6,947,024', '3,735,215'),
 ('Share Issued', '905,310', '863,013', '843,985', '807,805'),
 ('Ordinary Shares Number', '905,310', '863,013', '843,985', '807,805'),
 ('Learn more',
  'Advertise With Us',
  'Advertise With Us',
  '© 2020 Verizon Media. All rights reserved.',
  'Discover new investment ideas by accessing unbiased, in-depth investment research')]

In [126]:
balance_st = pd.DataFrame(is_data[0:])

In [127]:
balance_st

,0,1,2,3,4
0,Total Capitalization,"18,252,000","14,326,915","13,655,631","10,731,195"
1,Common Stock Equity,"6,618,000","4,923,243","4,237,242","4,752,911"
2,Capital Lease Obligations,"1,050,000","1,855,900","1,801,010","1,459,684"
3,Net Tangible Assets,"6,081,000","4,572,592","3,815,503","4,376,766"
4,Working Capital,"1,436,000","-1,685,828","-1,104,150","432,791"
5,Invested Capital,"20,037,000","16,894,614","14,552,180","11,881,342"
6,Tangible Book Value,"6,081,000","4,572,592","3,815,503","4,376,766"
7,Total Debt,"14,469,000","13,827,271","12,115,948","8,588,115"
8,Net Debt,"7,151,000","8,285,753","6,947,024","3,735,215"
9,Share Issued,"905,310","863,013","843,985","807,805"
10,Ordinary Shares Number,"905,310","863,013","843,985","807,805"
11,Learn more,Advertise With Us,Advertise With Us,© 2020 Verizon Media. All rights reserved.,Discover new investment ideas by accessing unb...